### ISSUE TITLE
modify ConvertToRate behaviour for aggregation plugin

### ISSUE THREAD

**Issue by farzadpanahi** [kairosdb/collectd-kairosdb#2]
original post: https://groups.google.com/forum/?hl=en#!topic/kairosdb-group/ao7Pl73JlnM

> ConvertToRate does a good job in converting to rate. I am using aggregation plugin to aggregate all cpu numbers from all cores. I want to apply ConvertToRate to all these aggregated cpu metrics. To do that I need to specify ConvertToRate "aggregation" in config file. But this will apply to all aggregations done by aggregation plugin. 
> 
> I think it would be better to let ConvertToRate accept something like "aggregation.cpu" to be able to control which plugin under aggregation needs rates.
> 
> What do you think?

jsabin's response:

> I opened up "issues" so you can add it as an issue.
> 
> What you are proposing is a little more difficult because there are four parts of a plugin; plugin, plugin_instance, type, type_instance. Which parts are you proposing ConvertToRate support? I guess ideally all four, but it complicates the code. 
> 
> Another solution that might be simpler would be to allow the actual value as well as the rate to be calculated. Perhaps a boolean config value to allow both?

**Comment by farzadpanahi** [comment]
I think the one that makes more sense is the "plugin" part. so for instance I think it makes sense to have something like the following in configuration:
`ConvertToRate "aggregation.cpu"`
I think taking care of other parts (plugin_instance, type, type_instance) may over complicate the configuration.

Also the other solution you provided for the binary flag I think is a good feature regardless of ConvertToRate.

**Comment by jsabin** [comment]
ConvertToRate currently takes a list of plugin names and converts all values for the plugins to a rate. For example, if you specify "cpu", all cpu values (and only cpu values) will be converted.

However, you are using "aggregation" plugin which is taking values from multiple plugins. Thus "plugin" is "aggregation" and "cpu" is probably "plugin_instance". I have never used the aggregation plugin so I don't know much how it works.

So your request is really to allow ConvertToRate to handle other parts such as plugin_instance. This is more complicated to specify and to implement. Perhaps you can offer a suggestion on how to specify what parts to match on (plugin, plugin_instance, type, type_instance).

It might required two properties; ConvertToRateFormat and ConvertToRate where ConvertToRateFormat would look something like "plugin.plugin_instance" and ConvertToRate would look like "aggregation.cpu". But that seems yucky. I'm open to suggestions.

**Comment by farzadpanahi** [comment]
This is how it looks like for cpu aggregation (when you have multiple cores)
https://collectd.org/wiki/index.php/Plugin:Aggregation/Config

```
<Plugin "aggregation">
  <Aggregation>
    Plugin "cpu"
    Type "cpu"

    GroupBy "Host"
    GroupBy "TypeInstance"

    CalculateSum true
    CalculateAverage true
  </Aggregation>
</Plugin>  
```

I think the goal here is to be able to specify that we want the aggregated cpu values to be converted to rate. So we just want a naming system to address the inner block of aggregation plugin which is responsible for cpu aggregation. in that case i think `aggregation.cpu` does the job well in addressing what we want to be converted to rate. 

One other way of looking at this is to create a boolean like ConvertToRateIncludeNested. Which when true will look into the plugins such as aggregation and if the nested plugin (like cpu) matches what is given in ConvertToRate list, then it will do the job for that nested plugin too. In this case we just need to have something like ConvertToRate "cpu" to take care of all cpu values and convert them to rate wherever they appear.

**Comment by jsabin** [comment]
The kairos plugin does not have access to the aggregator xml snippet.  Rather it gets call backs from collectd with the data and the naming parts (plugin, plugin_instance, type, type_instance). What the aggregator calls "plugin" is not what the kairos plugin receives as "plugin". Rather it gets "aggregation" as the plugin.
